#!/usr/bin/env python

import argparse
import os
import sys
from datetime import datetime

import fetch
import numpy as np


def check_required_arg(parser, arg):
    if not arg:
        parser.print_help()
        sys.exit(1)


parser = argparse.ArgumentParser(description="test")
parser.add_argument('-r', '--repository',
                    help="repository to fetch issues for (format: org/repo)",
                    default=os.getenv("REPOSITORY"))
parser.add_argument('--github-token',
                    help="GitHub token used to fetch issues from API",
                    default=os.getenv("GITHUB_TOKEN"))
parser.add_argument('--zenhub-token',
                    help="ZenHub token used to fetch issue events from REST API",
                    default=os.getenv("ZENHUB_TOKEN"))
parser.add_argument('-o', '--output',
                    help="Name of the file to save the commands result in. Default: stdout",
                    default=os.getenv("OUTPUT"))
args = parser.parse_args()


check_required_arg(parser, args.repository)
check_required_arg(parser, args.github_token)
check_required_arg(parser, args.zenhub_token)
fetch.fetch_issues(args.repository, "closed",
                   args.github_token, args.zenhub_token)
